Matrix/Models/ErrorViewModel.cs
namespace Matrix.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Matrix/Controllers/LocalPurchaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Controllers
{
    public class LocalPurchaseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_Add");
        }
    }
}

Matrix/Controllers/WareHouseController.cs
using Matrix.Core.Application;
using Matrix.Core.Application.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace Matrix.Controllers
{
    public class WareHouseController : Controller
    {

        private IRepositoryWrapper _repoWrapper;

        public async Task<IActionResult> Index()
        {
            //List<GetWareHouse> resp = await _repoWrapper.WareHouseRepo.GetWareHouse();
            return View(/*resp*/);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return PartialView("_Add");
        }

        [HttpPost]
        public async Task<JsonResult> Add(WareHouseDTO req)
        {
            JSONResultResp resp = new JSONResultResp();
            try
            {
                throw new Exception(req.WareHouseName + " is not a valid name for warehouse!");
                if (req == null)
                    throw new Exception("Kindly enter warehouse name");
                else
                {
                    _repoWrapper.WareHouseRepo.AddWareHouse(req);
                }
            }
            catch (Exception ex)
            {
                resp.hasError = true;
                resp.error = ex.Message;
            }

            return Json(resp);
        }
    }
}

Matrix/Controllers/_HomeController.cs
using Matrix.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Matrix.Controllers
{
    public class _HomeController : Controller
    {
        private readonly ILogger<_HomeController> _logger;

        public _HomeController(ILogger<_HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Matrix/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Matrix/Views/LocalPurchase/Index.cshtml
<div class="mb-3">
    <div class="form-inline justify-content-between col-md-12 mb-2">
        <div class="button">
            <div class="btn btn-primary btn-sm mb-2 add_btn">
                <i class="fa-solid fa-plus"></i> Add
            </div>
        </div>
        <section class="addSection"></section>
    </div>
    <!-------------- Table ----------------->
    <div class="container-fluid">
        <div class="tablecard small col-md-12">
            <table id="myTable" class="table table-striped table-bordered small">
                <thead>
                    <tr class="font-weight-bold">
                        <td>Customer ID</td>
                        <td>Customer Name</td>
                        <td>Customer Type</td>
                        <td>Customer Email</td>
                        <td>Customer Phone</td>
                        <td>Customer Address</td>
                        <td>Customer Country</td>
                        <td>Customer State</td>
                        <td>Customer City</td>
                        <td>Customer Postal Code</td>
                        <td>Edit</td>
                        <td>Delete</td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).on("click", ".add_btn", function () {
            $.ajax({
                url: '@Url.Action("Add","LocalPurchase")',
                type: "GET",
                success: function (resp){
                    $(".addSection").html(resp);
                    $("#addModalCenter").modal('show');
                }
            })
        });
    </script>
}

Matrix/Views/LocalPurchase/_Add.cshtml
<div>
    <div class="modal fade fullModal" id="addModalCenter" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Add Local Purchase</h5>
                    <button type="button" class="close add_btn" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="formTopbar">
                        <div class=" ">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Transaction Number
                                        </div>
                                        <input type="text" class="form-control" placeholder="" disabled>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Transaction Date
                                        </div>
                                        <input type="date" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Supplier
                                        </div>
                                        <input type="text" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Supplier Name
                                        </div>
                                        <input type="text" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Supplier Invoice#
                                        </div>
                                        <input type="text" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Invoice Date
                                        </div>
                                        <input type="date" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <table id="" class="table table-striped table-bordered small purchaseItems">
                                        <thead>
                                            <tr>
                                                <th>Material ID & Description</th>
                                                <th>Quantity</th>
                                                <th>Rate / Unit</th>
                                                <th>Amount</th>
                                                <th>WareHouse</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-4 txtSize">
                                            Payment Due Date
                                        </div>
                                        <input type="date" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="input-group input-group-sm mb-3">
                                        <input type="number" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-6">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-3 txtSize">
                                            Remarks*
                                        </div>
                                        <textarea class="form-control" placeholder="remarks"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-3 txtSize">
                                            Other
                                        </div>
                                        <input type="number" class="form-control" placeholder="">
                                        <div class="input-group-text col-sm-2 txtSize">
                                            ( + )
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6"></div>
                                <div class="col-md-4">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-3 txtSize">
                                            Discount
                                        </div>
                                        <input type="number" class="form-control" placeholder="">
                                        <div class="input-group-text col-sm-2 txtSize">
                                            ( - )
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-6"></div>
                                <div class="col-md-4">
                                    <div class="input-group input-group-sm mb-3">
                                        <div class="input-group-text col-sm-3 txtSize">
                                            Total
                                        </div>
                                        <input type="number" class="form-control" placeholder="">
                                    </div>
                                </div>
                                <div class="col-md-2"></div>

                            </div>

                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary m-2 col-md-2">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

    <script>
    $(document).ready(function () {
        const editor = new DataTable.Editor({
            //ajax: '../php/staff.php',
            fields: [
                {
                    label: 'First name:',
                    name: 'first_name'
                },
                {
                    label: 'Last name:',
                    name: 'last_name'
                },
                {
                    label: 'Position:',
                    name: 'position'
                },
                {
                    label: 'Office:',
                    name: 'office'
                },
                {
                    label: 'Extension:',
                    name: 'extn'
                },
                {
                    label: 'Start date:',
                    name: 'start_date',
                    type: 'datetime'
                },
                {
                    label: 'Salary:',
                    name: 'salary'
                }
            ],
            table: '#example'
        });
        const table = new DataTable('.purchaseItems', {
            columns: [
                {
                    data: null,
                    defaultContent: '',
                    className: 'select-checkbox',
                    orderable: false
                },
                { data: 'first_name' },
                { data: 'last_name' },
                { data: 'office' },
                { data: 'start_date' },
                { data: 'salary', render: DataTable.render.number(null, null, 0, '$') }
            ],
            dom: 'Bfrtip',
            order: [[1, 'asc']],
            select: {
                style: 'os',
                selector: 'td:first-child'
            }
        });
        });
        
    </script>
@section scripts{
}

Matrix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Matrix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Matrix.styles.css" asp-append-version="true" />
    <script src="~/js/kit.fontawesome.js"></script>
    <script src="~/js/xlsx.full.min.js"></script>
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/jquery-3.6.0.min.js"></script>
    <script src="~/js/jquery-datatables.min.js"></script>
    <script src="~/js/bootstrap.min-4.js"></script>
    <script src="~/js/datatables.button.min.js"></script>
    <link rel="stylesheet" href="~/css/bootstrap.min-4.css">
    <link rel="stylesheet" href="~/css/bootstrap.min-5.css">
    <link rel="stylesheet" href="~/css/datatables.min.css">
    <link rel="stylesheet" href="~/css/databtables.bootstrap.buttons.min.css">
    <link rel="stylesheet" href="~/css/sideBarStyle.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/datatableStyle.css" asp-append-version="true">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"/>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <aside id="sidebar">
            <div class="h-100">
                <div class="sidebar-logo">
                    <a href="dashboard.html">INOVI SOLUTIONS</a>
                </div>
                <ul id="sideBarMenus" class="sidebar-nav">
                    <!-- Generated SideBar -->
                </ul>
            </div>
        </aside>

        <!-- Main Component -->
        <div class="main">
            <nav class="navbar navbar-expand px-3 border-bottom">
                <!-- Button for sidebar toggle -->
                <button id="toggle_btn" class="btn" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navRightMenus">
                    <ul class="navbar-nav">
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider" />
                                </li>
                                <li><a class="dropdown-item" href="login.html">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="content px-3 py-2">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
    <script src="~/js/dataTableScript.js"></script>
    <script src="~/js/datatables.bootstrap.buttons.js"></script>
    <script src="~/js/bootstrap.bundle.min-5.js"></script>
    <script src="~/js/sideBarScript.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>

Matrix/Views/WareHouse/Index.cshtml
<div class="mb-3">
    <div class="form-inline justify-content-between col-md-12 mb-2">
        <div class="button">
            <div class="btn btn-primary btn-sm mb-2 add_btn btn-block">
                <i class="fa-solid fa-plus"></i> Add
            </div>
        </div>
        <section class="addSection"></section>
    </div>
    <!-------------- Table ----------------->
    <div class="container-fluid">
        <div class="tablecard small col-md-12">
            <table id="myTable" class="table table-striped table-bordered small">
                <thead>
                    <tr class="font-weight-bold">
                        <td></td>
                        <td>Warehouse ID</td>
                        <td>Warehouse Name</td>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).on("click", ".add_btn", function (e) {
            let target = e.currentTarget;
            loader(target, true);

            $.ajax({
                url: '@Url.Action("Add","WareHouse")',
                type: "GET",
                success: function (resp) {
                    $(".addSection").html(resp);
                    $("#addModalCenter").modal('show');
                    loader(target, false);
                }
            })
        });


        $(document).on('click', '.addWareHouse', function (e) {
            e.preventDefault();
            let target = e.currentTarget;
            let wName = $('.warehouseName').val();
            if (wName != null && wName != "") {
                loader(target, true);
                $.ajax({
                    url: '@Url.Action("Add","WareHouse")',
                    type: "POST",
                    data: {
                        WareHouseName: wName
                    },
                    success: function (resp) {
                        loader(target, false);
                    }
                })
            }
        })
    </script>
}

Matrix/Views/WareHouse/_Add.cshtml
<div class="modal fade fullModal" id="addModalCenter" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add WareHouse</h5>
                <button type="button" class="close add_btn" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="formTopbar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="input-group input-group-sm mb-3">
                                <div class="input-group-text col-sm-4 txtSize">
                                    WareHouse Name
                                </div>
                                <input type="text" class="form-control warehouseName" placeholder="">
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="btn btn-primary btn-block addWareHouse">
                                Add WareHouse
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>